name: Code Coverage

on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "dynrender_skia/**/*"
      - "tests/**/*"
      - ".github/workflows/codecov.yml"
  pull_request:
    paths:
      - "dynrender_skia/**/*"
      - "tests/**/*"
      - ".github/workflows/codecov.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run pytest --cov=dynrender_skia --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
